name: Build and Deploy ec2

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        # .ssh 디렉토리와 known_hosts 파일 생성
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # EC2 서버로 파일 직접 전송
      - name: Deploy to EC2
        run: scp -r dist/* ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/myblog
        env:
          SSH_AUTH_SOCK: ${{ steps.ssh-agent.outputs.ssh-auth-sock }}
