name: Build and Deploy to EC2

on:
  push:
    branches: [main] # 메인 브랜치에 푸시될 때만 작동

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x' # 사용할 Node.js 버전

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # 빌드 스크립트 실행

      - name: Upload dist to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download dist from Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          password: ${{ secrets.EC2_PASSWORD }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            sudo scp -r dist/* ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/myblog/myblog_backend
            sudo ssh ubuntu@${{ secrets.EC2_HOST }} "cd /home/ubuntu/myblog/myblog_backend && pm2 start dist/app.js"
