name: Deploy to EC2

on:
  push:
    branches: [main] # 메인 브랜치에 푸시될 때만 작동

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: git config --global --add safe.directory /home/ubuntu/myblog_typescript

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/myblog
            sudo git pull
            sudo pm2 restart app
