name: dev branch auto ci process script

on: # 아래 job을 실행시킬 상황
  push:
    branches: [dev]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest # 실행될 인스턴스 OS와 버전

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.EC2_HOST }} # 인스턴스 IP
          username: ${{ secrets.EC2_USER }} # 우분투 아이디
          key: ${{ secrets.EC2_SSH_KEY }} # ec2 instance pem key
          port: ${{ secrets.EC2_PORT }} # 접속포트
          script: | # 실행할 스크립트
            cd /home/ubuntu/myblog
            git pull
            pm2 kill
            npm i --force
            npm run build
            pm2 start dist/app.js
